name: Windows Event Log Application 2282
id: 4490537e-5e0c-46f7-9209-f56f852aa237
version: 1
date: '2024-07-18'
author: Patrick Bareiss, Splunk
description: Data source object for Windows Event Log Application 2282
source: XmlWinEventLog:Application
sourcetype: XmlWinEventLog
separator: EventCode
supported_TA:
- name: Splunk Add-on for Microsoft Windows
  url: https://splunkbase.splunk.com/app/742
  version: 8.9.0
fields:
- _time
- Channel
- Computer
- Error_Code
- EventCode
- EventData_Xml
- EventRecordID
- EventSourceName
- Guid
- Keywords
- Level
- ModuleDll
- Name
- Opcode
- ProcessID
- ProcessorArchitecture
- Qualifiers
- RecordNumber
- SystemTime
- System_Props_Xml
- Task
- ThreadID
- Version
- date_hour
- date_mday
- date_minute
- date_month
- date_second
- date_wday
- date_year
- date_zone
- dest
- dvc
- dvc_nt_host
- event_id
- eventtype
- host
- id
- index
- linecount
- punct
- signature_id
- source
- sourcetype
- splunk_server
- tag
- tag::eventtype
- timeendpos
- timestartpos
- vendor_product
example_log: <Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider
  Name='Microsoft-Windows-IIS-W3SVC-WP' Guid='{670080D9-742A-4187-8D16-41143D1290BD}'
  EventSourceName='W3SVC-WP'/><EventID Qualifiers='49152'>2282</EventID><Version>0</Version><Level>2</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x80000000000000</Keywords><TimeCreated
  SystemTime='2022-12-20T15:58:25.325383600Z'/><EventRecordID>1001307</EventRecordID><Correlation/><Execution
  ProcessID='0' ThreadID='0'/><Channel>Application</Channel><Computer>win-dc-exch01.attackrange.local</Computer><Security/></System><EventData><Data
  Name='ModuleDll'>c:\temp\msf.dll</Data><Data Name='ProcessorArchitecture'>AMD64</Data><Binary>C1000000</Binary></EventData></Event>
