name: Azure AD User Consent Denied for OAuth Application
id: bb093c30-d860-4858-a56e-cd0895d5b49c
version: 3
date: '2024-05-18'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source:
- Azure Active Directory Sign-in activity
description: The following analytic identifies instances where a user has denied consent
  to an OAuth application seeking permissions within the Azure AD environment. This
  detection leverages Azure AD's audit logs, specifically focusing on user consent
  actions with error code 65004. Monitoring denied consent actions is significant
  as it can indicate users recognizing potentially suspicious or untrusted applications.
  If confirmed malicious, this activity could suggest attempts by unauthorized applications
  to gain access, potentially leading to data breaches or unauthorized actions within
  the environment. Understanding these denials helps refine security policies and
  enhance user awareness.
search: ' `azure_monitor_aad` operationName="Sign-in activity" properties.status.errorCode=65004
  | rename properties.* as * | stats count min(_time) as firstTime max(_time) as lastTime
  by operationName, user, appDisplayName, status.failureReason | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `azure_ad_user_consent_denied_for_oauth_application_filter`'
how_to_implement: You must install the latest version of Splunk Add-on for Microsoft
  Cloud Services from Splunkbase (https://splunkbase.splunk.com/app/3110/#/details).
  You must be ingesting Azure Active Directory events into your Splunk environment
  through an EventHub. This analytic was written to be used with the azure:monitor:aad
  sourcetype leveraging the SignInLogs log category.
known_false_positives: Users may deny consent for legitimate applications by mistake,
  filter as needed.
references:
- https://attack.mitre.org/techniques/T1528/
- https://www.microsoft.com/en-us/security/blog/2022/09/22/malicious-oauth-applications-used-to-compromise-email-servers-and-spread-spam/
- https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/protect-against-consent-phishing
- https://learn.microsoft.com/en-us/defender-cloud-apps/investigate-risky-oauth
- https://www.alteredsecurity.com/post/introduction-to-365-stealer
- https://github.com/AlteredSecurity/365-Stealer
tags:
  analytic_story:
  - Azure Active Directory Account Takeover
  asset_type: Azure Tenant
  confidence: 60
  impact: 60
  message: User $user$ denied consent for an OAuth application.
  mitre_attack_id:
  - T1528
  observable:
  - name: user
    type: User
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 36
  required_fields:
  - _time
  - operationName
  - properties.status.errorCode
  - user
  - properties.appDisplayName
  - status.failureReason
  security_domain: identity
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1528/azure_ad_user_consent_declined/azure_ad_user_consent_declined.log
    source: Azure AD
    sourcetype: azure:monitor:aad
