name: O365 Mail Permissioned Application Consent Granted by User
id: fddad083-cdf5-419d-83c6-baa85e329595
version: 2
date: '2024-05-14'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source:
- O365 Consent to application.
description: The following analytic identifies instances where a user grants consent
  to an application requesting mail-related permissions within the Office 365 environment.
  It leverages O365 audit logs, specifically focusing on events related to application
  permissions and user consent actions. This activity is significant as it can indicate
  potential security risks, such as data exfiltration or spear phishing, if malicious
  applications gain access. If confirmed malicious, this could lead to unauthorized
  data access, email forwarding, or sending malicious emails from the compromised
  account. Validating the legitimacy of the application and consent context is crucial
  to prevent data breaches.
search: >-
  `o365_management_activity` Workload=AzureActiveDirectory Operation="Consent to application."
  ResultStatus=Success
  | eval admin_consent =mvindex('ModifiedProperties{}.NewValue', 0)
  | search admin_consent=False
  | eval permissions =mvindex('ModifiedProperties{}.NewValue', 4)
  | rex field=permissions "Scope: (?<Scope>[^,]+)"
  | makemv delim=" " Scope
  | search Scope IN ("Mail.Read", "Mail.ReadBasic", "Mail.ReadWrite", "Mail.Read.Shared",
  "Mail.ReadWrite.Shared", "Mail.Send", "Mail.Send.Shared")
  | stats max(_time) as lastTime values(Scope) by Operation, user, object, ObjectId
  | `security_content_ctime(lastTime)`
  | `o365_mail_permissioned_application_consent_granted_by_user_filter`
how_to_implement: You must install the Splunk Microsoft Office 365 Add-on and ingest
  Office 365 management activity events.
known_false_positives: OAuth applications that require mail permissions may be legitimate,
  investigate and filter as needed.
references:
- https://attack.mitre.org/techniques/T1528/
- https://www.microsoft.com/en-us/security/blog/2022/09/22/malicious-oauth-applications-used-to-compromise-email-servers-and-spread-spam/
- https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/protect-against-consent-phishing
- https://learn.microsoft.com/en-us/defender-cloud-apps/investigate-risky-oauth
- https://www.alteredsecurity.com/post/introduction-to-365-stealer
- https://github.com/AlteredSecurity/365-Stealer
tags:
  analytic_story:
  - Office 365 Account Takeover
  asset_type: O365 Tenant
  confidence: 50
  impact: 80
  message: User $user$ consented an OAuth application that requests mail-related permissions.
  mitre_attack_id:
  - T1528
  observable:
  - name: user
    type: User
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 40
  required_fields:
  - _time
  - Workload
  - Operation
  - ResultStatus
  - ModifiedProperties{}.NewValue
  - object
  - ObjectId
  security_domain: identity
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1528/o365_user_consent_mail_permissions/o365_user_consent_mail_permissions.log
    source: o365
    sourcetype: o365:management:activity

