name: Linux Possible Append Command To At Allow Config Filedasdasdasdasdasdasdasdasdasdasdasdaadsadasdasdasdasd
id: 7bc20606-5f40-11ec-a586-acde48001122
version: 2
date: '2022-05-26'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic is designed to identify suspicious command lines that may append user entries to either /etc/at.allow or /etc/at.deny. These files can be exploited by malicious actors for persistence on a compromised Linux host by altering permissions for scheduled tasks using the at command.\

  In this context, an attacker can create a user or add an existing user to these configuration files to execute their malicious code through scheduled tasks. The detection of such anomalous behavior can serve as an effective indicator warranting further investigation to validate if the activity is indeed malicious or a false positive.
data_source:
- Sysmon Event ID 1
search:
  selection1:
    CommandLine:
    - '*/etc/at.allow'
    - '*/etc/at.deny'
  selection2:
    CommandLine: '*echo*'
  condition: selection1 and selection2
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you can use the Add-on for Linux Sysmon from
  Splunkbase.
known_false_positives: False positives may occur when administrators or network operators use similar command lines for legitimate automation purposes. Therefore, it is recommended to update filter macros to reduce such instances.
references:
- https://linuxize.com/post/at-command-in-linux/
- https://attack.mitre.org/techniques/T1053/001/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  asset_type: Endpoint
  confidence: 30
  impact: 30
  message: A commandline $process$ that may modify at allow config file in $dest$
  mitre_attack_id:
  - T1053.002
  - T1053
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 9
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1053.002/at_execution/sysmon_linux.log
    source: Syslog:Linux-Sysmon/Operational
    sourcetype: sysmon_linux
