name: Windows Ingress Tool Transfer Using Explorer
id: 695bfad6-9662-4f9e-a576-bf02a951aa60
version: 1
date: '2022-09-13'
author: Michael Haag, Splunk
status: production
type: TTP
description: The following analytic identifies the Windows Explorer process with a
  URL within the command-line. Explorer.exe is known Windows process that handles
  start menu, taskbar, desktop and file manager. Many adversaries abuse this process,
  like DCRat malware, where it attempts to open the URL with the default browser application
  on the target host by putting the URL as a parameter on explorer.exe process. This
  anomaly detection might be a good pivot to check which user and how this process
  was executed, what is the parent process and what is the URL link. This technique
  is not commonly used to open an URL.
data_source: []
search: '| from read_ssa_enriched_events() | eval timestamp=parse_long(ucast(map_get(input_event,
  "_time"), "string", null)), cmd_line=lower(ucast(map_get(input_event, "process"),
  "string", null)), process_name=lower(ucast(map_get(input_event, "process_name"),
  "string", null)), process_path=ucast(map_get(input_event, "process_path"), "string",
  null), parent_process_name=ucast(map_get(input_event, "parent_process_name"), "string",
  null), event_id=ucast(map_get(input_event, "event_id"), "string", null) | where
  cmd_line IS NOT NULL AND process_name IS NOT NULL | where process_name="explorer.exe"
  AND (like (cmd_line, "%http://%") OR like (cmd_line, "%https://%")) AND NOT (like(parent_process_name,
  "userinit.exe") OR like(parent_process_name, "svchost.exe")) | eval start_time=timestamp,
  end_time=timestamp, entities=mvappend(ucast(map_get(input_event, "dest_user_id"),
  "string", null), ucast(map_get(input_event, "dest_device_id"), "string", null)),
  body=create_map(["event_id", event_id, "cmd_line", cmd_line, "process_name", process_name,
  "parent_process_name", parent_process_name, "process_path", process_path]) | into
  write_ssa_detected_events();'
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints.
known_false_positives: False positives may be present based on legitimate applications
  or third party utilities. Filter out any additional parent process names.
references:
- https://www.mandiant.com/resources/analyzing-dark-crystal-rat-backdoor
tags:
  analytic_story:
  - DarkCrystal RAT
  asset_type: Endpoint
  atomic_guid: []
  confidence: 50
  drilldown_search: []
  impact: 50
  message: An instance of $parent_process_name$ spawning $process_name$ was identified
    on endpoint $dest_device_id$ by user $dest_user_id$ attempting to access a remote
    destination to download an additional payload.
  mitre_attack_id:
  - T1105
  product:
  - Splunk Behavioral Analytics
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1105/atomic_red_team/T1105_explorer-windows-security.log
    source: XmlWinEventLog
    sourcetype: XmlWinEventLog
    update_timestamp: true
