name: Detect Prohibited Applications Spawning cmd exe
id: c10a18cb-fd80-4ffa-a844-25026e0a0c94
version: 3
date: '2022-03-01'
author: Ignacio Bermudez Corrales, Splunk
type: Anomaly
status: production
description: The following analytic identifies parent processes, browsers, Windows
  terminal applications, Office Products and Java spawning cmd.exe. By its very nature,
  many applications spawn cmd.exe natively or built into macros. Much of this will
  need to be tuned to further enhance the risk.
data_source:
- Windows Security 4688
search: ' | from read_ba_enriched_events() | eval timestamp = ucast(map_get(input_event,"time"),"long",
  null) | eval origin = ucast(map_get(input_event, "origin"),"map<string, any>", null)
  | eval metadata = ucast(map_get(input_event, "metadata"),"map<string, any>", null)
  | eval metadata_uid = ucast(map_get(metadata, "uid"),"string", null) | eval process=ucast(map_get(input_event,"process"),
  "map<string, any>", null) | eval process_pid=ucast(map_get(process,"pid"), "string",
  null) | eval process_file=ucast(map_get(process,"file"), "map<string, any>", null)
  | eval process_file_path=ucast(map_get(process_file,"path"), "string", null) | eval
  process_file_name=ucast(map_get(process_file,"name"), "string", null) | eval process_cmd_line=ucast(map_get(process,"cmd_line"),
  "string", null) | eval process_user=ucast(map_get(process,"user"), "map<string,
  any>", null) | eval process_user_name=ucast(map_get(process_user,"name"), "string",
  null) | eval actor=ucast(map_get(input_event,"actor"), "map<string, any>", null)
  | eval actor_process=ucast(map_get(actor,"process"), "map<string, any>", null) |
  eval actor_process_pid=ucast(map_get(actor_process,"pid"), "string", null) | eval
  actor_process_file=ucast(map_get(actor_process,"file"), "map<string, any>", null)
  | eval actor_process_file_path=ucast(map_get(actor_process_file,"path"), "string",
  null) | eval actor_process_file_name=ucast(map_get(actor_process_file,"name"), "string",
  null) | eval device=ucast(map_get(input_event,"device"), "map<string, any>", null)
  | eval device_hostname=ucast(map_get(device,"hostname"), "string", null) | where
  (actor_process_file_name="winword.exe" OR actor_process_file_name="excel.exe" OR
  actor_process_file_name="outlook.exe" OR actor_process_file_name="acrobat.exe" OR
  actor_process_file_name="acrord32.exe" OR actor_process_file_name="iexplore.exe"
  OR actor_process_file_name="opera.exe" OR actor_process_file_name="firefox.exe"
  OR actor_process_file_name="powershell.exe") OR (actor_process_file_name="java.exe"
  AND (NOT match_regex(actor_process_file_name, /(?i)patch1-Hotfix1a/)=true)) OR (actor_process_file_name="chrome.exe"
  AND (NOT process_cmd_line="chrome-extension")) --finding_report--'
how_to_implement: In order to successfully implement this analytic, you will need
  endpoint process data from a EDR product or Sysmon. This search has been modified
  to process raw sysmon data from attack_range's nxlogs on DSP.
known_false_positives: There are circumstances where an application may legitimately
  execute and interact with the Windows command-line interface.
references:
- https://attack.mitre.org/techniques/T1059/
tags:
  analytic_story:
  - Suspicious Command-Line Executions
  - Insider Threat
  asset_type: Endpoint
  confidence: 50
  impact: 70
  message: An instance of $parent_process_name$ spawning $process_name$ was identified
    on endpoint $dest_device_id$ by user $dest_user_id$, producing a suspicious event
    that warrants investigating.
  mitre_attack_id:
  - T1059
  observable:
  - name: process.user.name
    type: User Name
  - name: device.hostname
    type: Hostname
  - name: process.cmd_line
    type: Other
  - name: actor.process.file.name
    type: File Name
  product:
  - Splunk Behavioral Analytics
  required_fields:
  - process.user.name
  - device.hostname
  - process.cmd_line
  - actor.process.file.name
  risk_score: 35
  security_domain: endpoint
  mappings:
  - ocsf: process.pid
    cim: process_id
  - ocsf: process.file.path
    cim: process_path
  - ocsf: process.file.name
    cim: process_name
  - ocsf: process.cmd_line
    cim: process
  - ocsf: process.user.name
    cim: user
  - ocsf: actor.process.pid
    cim: parent_process_id
  - ocsf: actor.process.file.path
    cim: parent_process_path
  - ocsf: actor.process.file.name
    cim: parent_process_name
  - ocsf: device.hostname
    cim: dest
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1059.003/powershell_spawn_cmd/windows-security.log
    source: WinEventLog:Security
