definition: eventtype=wineventlog_application OR source="XmlWinEventLog:Application"
description: customer specific splunk configurations(eg- index, source, sourcetype).
  Replace the macro definition with configurations for your Splunk Environmnent.
name: wineventlog_application