name: Windows Ingress Tool Transfer Using Explorer
id: 695bfad6-9662-4f9e-a576-bf02a951aa60
version: 1
date: '2022-09-13'
author: Michael Haag, Splunk
status: production
type: TTP
description: The following analytic identifies the Windows Explorer process with a
  URL within the command-line. Explorer.exe is known Windows process that handles
  start menu, taskbar, desktop and file manager. Many adversaries abuse this process,
  like DCRat malware, where it attempts to open the URL with the default browser application
  on the target host by putting the URL as a parameter on explorer.exe process. This
  anomaly detection might be a good pivot to check which user and how this process
  was executed, what is the parent process and what is the URL link. This technique
  is not commonly used to open an URL.
data_source:
- Windows Security 4688
search:
  selection1:
    process.cmd_line|contains:
    - https://
    - http://
    process.file.name: explorer.exe
  condition: (selection1)
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints.
known_false_positives: False positives may be present based on legitimate applications
  or third party utilities. Filter out any additional parent process names.
references:
- https://www.mandiant.com/resources/analyzing-dark-crystal-rat-backdoor
tags:
  analytic_story:
  - DarkCrystal RAT
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: An instance of $parent_process_name$ spawning $process_name$ was identified
    on endpoint $dest_device_id$ by user $dest_user_id$ attempting to access a remote
    destination to download an additional payload.
  mitre_attack_id:
  - T1105
  observable: []
  product:
  - Splunk Behavioral Analytics
  required_fields: []
  kill_chain_phases:
  - Exploitation
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1105/atomic_red_team/T1105_explorer-windows-security.log
    source: XmlWinEventLog
    sourcetype: XmlWinEventLog
    update_timestamp: true
