name: AWS IAM Account Unlocking
id: f15a4db3-b157-4225-86ae-c36ab78b50f2
version: 1
date: '2023-6-21'
author: Lou Stella, Splunk
type: Response
description: "Accepts user, to be enabled using AWS IAM connector. This playbook produces a normalized observables output for each user. "
playbook: AWS_IAM_Account_Unlocking
how_to_implement: This input playbook requires the AWS IAM connector to be configured. 
references: []
app_list: 
  - AWS IAM
tags:
  platform_tags:
    - user
    - aws_iam
    - D3-AL
    - enable_account
  playbook_type: Input
  vpe_type: Modern
  playbook_fields: []
  product:
  - Splunk SOAR