name: Internal Host WinRM Log4j Investigate
id: 2cf7c9f4-b273-44f6-a27c-e0db668ff05a
version: 1
date: '2021-12-14'
author: Kelby Shelton, Splunk
type: Investigation
description: Published in response to CVE-2021-44228, this playbook uses WinRM to scan Windows endpoints for the presence of "jndilookup.class" in all .jar files. The presence of that string could indicate a log4j vulnerability.
playbook: internal_host_winrm_log4j_investigate
how_to_implement: The winrm asset requires Administrator access to scan the whole file system.
references: ["https://twitter.com/CyberRaiju/status/1469505677580124160"]
app_list:
- "Windows Remote Management"
tags:
  platform_tags: []
  playbook_type: Input
  vpe_type: Modern
  playbook_fields: []
  product:
  - Splunk SOAR
