name: Internal Host WinRM Investigate
id: 32fd9db5-5201-4a2f-b2c2-9299c7b3495d
version: 1
date: '2021-12-14'
author: Kelby Shelton, Splunk
type: Investigation
description: Performs a general investigation on key aspects of a windows device using windows remote management. Important files related to the endpoint are generated, bundled into a zip, and copied to the container vault.
playbook: internal_host_winrm_investigate
how_to_implement: The winrm asset requires Administrator access to gather certain files.
references: []
app_list:
- "Windows Remote Management"
tags:
  platform_tags: []
  playbook_type: Input
  vpe_type: Modern
  playbook_fields: []
  product:
  - Splunk SOAR
