name: Malware Hunt and Contain
id: fb3edc76-ff2b-43c0-5f6f-63da4483fd63
version: 1
date: '2021-01-21'
author: Philip Royer, Splunk
type: Response
description: This playbook investigates and remediates malware infections on the endpoint.
playbook: malware_hunt_and_contain
how_to_implement: "Be sure to update asset naming to reflect the asset names configured in your environment."
references: []
app_list:
- "LDAP"
- "ServiceNow"
- "Carbon Black Response"
- "VirusTotal"
tags:
  platform_tags: []
  playbook_type: Automation
  vpe_type: Classic
  playbook_fields:
  - fileHash
  product:
  - Splunk SOAR