name: MS Graph for Office 365 Message Restore
id: 5299d6dd-e9c4-4bad-b041-928ace1ff811
version: 1
date: '2024-02-15'
author: Lou Stella, Splunk
type: Response
description: Accepts message ID that needs to be restored to the provided email mailbox in Microsoft Office365. Generates an observable output based on the status of message restoration.
playbook: MS_Graph_for_Office_365_Message_Restore
how_to_implement: This input playbook requires the MS Graph for Office 365 connector to be configured.  
references: []
app_list: 
  - MS Graph for Office 365
tags:
  platform_tags:
    - message_restore 
    - internet_message_id
    - email
    - ms_graph_for_o365
  playbook_type: Input
  vpe_type: Modern
  playbook_fields: []
  product:
  - Splunk SOAR
  use_cases:
  - Phishing
  defend_technique_id: 
  - D3-RE