name: Panorama Outbound Traffic Filtering
id: 5e3e061f-5206-49ac-88f4-4e818a20b2a9
version: 1
date: '2023-05-19'
author: Patrick Bareiss, Splunk
type: Response
description: Accepts a URL or list of URLs as input. Uses Panorama to block the given URLs in Palo Alto Firewall.
playbook: Panorama_Outbound_Traffic_Filtering
how_to_implement: This input playbook requires the Panorama connector to be configured. It is designed to work in conjunction with the Dynamic URL Outbound Traffic Filtering Analysis playbook or other playbooks in the same style.
references: 
- https://d3fend.mitre.org/technique/d3f:OutboundTrafficFiltering/
app_list: 
  - Panorama
tags:
  platform_tags:
    - denylist
    - url
    - Panorama
  playbook_type: Input
  vpe_type: Modern
  playbook_fields: []
  product:
  - Splunk SOAR
  use_cases:
  - Phishing
  - Endpoint
  defend_technique_id: 
  - D3-OTF
