name: Risk Notable Merge Events
id: rn0edc96-ff2b-48b0-9f6f-53da3783fd63
version: 1
date: "2021-10-22"
author: Kelby Shelton, Splunk
type: Investigation
description: This playbook finds related events based on key fields in a risk notable and allows the user to process the results and decide which events to merge into the current investigation.
playbook: risk_notable_merge_events
how_to_implement: Combining the list_merge utility within the playbook with the find_related_containers utility allows for fine-tuning of related event criteria. For example, the default filtering criteria uses description, risk_object, and threat_object as the important fields and requires at least three matches before an event is considered related. There are several options to customize the associated criteria, including adding more fields in list_merge, reducing or increasing the minimum match count, or utilizing the wildcard feature of find_related_containers.
references:
- https://docs.splunk.com/Documentation/ESSOC/latest/user/Useplaybookpack
app_list:
  - "None"
tags:
  labels:
  - risk_notable
  playbook_outputs:
  - note_title
  - note_content
  playbook_type: Automation
  platform_tags:
  - Risk Notable
  product:
  - Splunk SOAR
