name: Risk Notable Verdict
id: rn0edc96-ff2b-48b0-9f6f-33da3783fd63
version: 1
date: "2021-10-22"
author: Kelby Shelton, Splunk
type: Response
description: This playbook locates available playbooks with the response tag and presents them to the analyst. Based on the analyst selection, it will launch its chosen playbook.
playbook: risk_notable_verdict
how_to_implement: tbd
references:
- https://docs.splunk.com/Documentation/ESSOC/latest/user/Useplaybookpack#Call_child_playbooks_with_the_dynamic_playbook_system
app_list:
  - "None"
tags:
  labels:
  - risk_notable
  platform_tags:
  - Risk Notable
  playbook_type: Automation
  product:
  - Splunk SOAR
