name: Risk Notable Enrich
id: rn0edc96-ff2b-48b0-9f6f-43da3783fd63
version: 1
date: "2021-10-22"
author: Kelby Shelton, Splunk
type: Investigation
description: This playbook collects the available Indicator data types within the event as well as available investigative playbooks. It will launch any playbooks that meet the filtered criteria.
playbook: risk_notable_enrich
how_to_implement: tbd
references:
- https://docs.splunk.com/Documentation/ESSOC/latest/user/Useplaybookpack#Call_child_playbooks_with_the_dynamic_playbook_system
app_list: 
  - "None"
tags:
  labels:
  - risk_notable
  playbook_outputs:
  - note_title
  - note_content
  playbook_type: Automation
  platform_tags:
  - Risk Notable
  product:
  - Splunk SOAR
