name: Risk Notable Investigate
id: rn0edc96-ff2b-48b0-9f6f-03da3783fd63
version: 1
date: "2021-10-22"
author: Kelby Shelton, Splunk
type: Investigation
description: This playbook checks for the presence of the Risk Investigation workbook and updates tasks or leaves generic notes.
playbook: risk_notable_investigate
how_to_implement: Set this playbook to run in Active mode on the Risk Notable label in Splunk SOAR.
references:
- https://docs.splunk.com/Documentation/ESSOC/latest/user/Useplaybookpack
app_list:
  - "None"
tags:
  labels:
  - risk_notable
  playbook_type: Automation
  platform_tags:
  - Risk Notable
  product:
  - Splunk SOAR
