name: Splunk Protocol Impersonation Weak Encryption Configuration
id: 900892bf-70a9-4787-8c99-546dd98ce461
version: 1
date: '2022-05-25'
author: Lou Stella, Splunk
status: production
type: Hunting
description: On June 14th, 2022, Splunk released a security advisory relating to TLS
  validation occuring within the httplib and urllib python libraries shipped with
  Splunk. In addition to upgrading to Splunk Enterprise 9.0 or later, several configuration
  settings need to be set. This search will check those configurations on the search
  head it is run from as well as its search peers. In addition to these settings,
  the PYTHONHTTPSVERIFY setting in $SPLUNK_HOME/etc/splunk-launch.conf needs to be
  enabled as well. Other components such as additional search heads or anything this
  rest command cannot be distributed to will need to be manually checked.
data_source: []
search: '| rest /services/server/info | table splunk_server version server_roles |
  join splunk_server [| rest /servicesNS/nobody/search/configs/conf-server/ search="PythonSslClientConfig"
  | table splunk_server sslVerifyServerCert sslVerifyServerName] | join splunk_server
  [| rest /servicesNS/nobody/search/configs/conf-web/settings |  table splunk_server
  serverCert sslVersions] | rename sslVerifyServerCert as "Server.conf:PythonSSLClientConfig:sslVerifyServerCert",
  sslVerifyServerName as "Server.conf:PythonSSLClientConfig:sslVerifyServerName",
  serverCert as "Web.conf:Settings:serverCert", sslVersions as "Web.conf:Settings:sslVersions"
  | `splunk_protocol_impersonation_weak_encryption_configuration_filter`'
how_to_implement: The user running this search is required to have a permission allowing
  them to dispatch REST requests to indexers (The `dispatch_rest_to_indexers` capability).
  Splunk SOAR customers can find a SOAR workbook that walks an analyst through the
  process of running these hunting searches in the references list of this detection.
  In order to use this workbook, a user will need to run a curl command to post the
  file to their SOAR instance such as "curl -u username:password https://soar.instance.name/rest/rest/workbook_template
  -d @splunk_psa_0622.json". A user should then create an empty container or case,
  attach the workbook, and begin working through the tasks.
known_false_positives: While all of the settings on each device returned by this search
  may appear to be hardened, you will still need to verify the value of PYTHONHTTPSVERIFY
  in $SPLUNK_HOME/etc/splunk-launch.conf on each device in order to harden the python
  configuration.
references:
- https://docs.splunk.com/Documentation/Splunk/9.0.0/Security/EnableTLSCertHostnameValidation
- https://www.splunk.com/en_us/product-security/announcements/svd-2022-0601.html
- https://www.github.com/splunk/security_content/blob/develop/workbooks/splunk_psa_0622.json
tags:
  analytic_story:
  - Splunk Vulnerabilities
  asset_type: Endpoint
  confidence: 100
  cve:
  - CVE-2022-32151
  impact: 50
  message: $splunk_server$ may not be properly validating TLS Certificates
  mitre_attack_id:
  - T1001.003
  observable:
  - name: splunk_server
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - none
  risk_score: 50
  security_domain: threat
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1213/audittrail/audittrail.log
    source: audittrail
    sourcetype: audittrail
    update_timestamp: true
    custom_index: _audit
