name: Change To Safe Mode With Network Config
id: 81f1dce0-0f18-11ec-a5d7-acde48001122
version: 2
date: '2024-05-26'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic detects the execution of a suspicious `bcdedit`
  command that configures a host to boot in safe mode with network support. It leverages
  data from Endpoint Detection and Response (EDR) agents, focusing on command-line
  executions involving `bcdedit.exe` with specific parameters. This activity is significant
  because it is a known technique used by BlackMatter ransomware to force a compromised
  host into safe mode for continued encryption. If confirmed malicious, this could
  allow attackers to bypass certain security controls, persist in the environment,
  and continue their malicious activities.
data_source:
- Sysmon EventID 1
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where Processes.process_name = bcdedit.exe
  Processes.process="*/set*" Processes.process="*{current}*"  Processes.process="*safeboot*"
  Processes.process="*network*" by Processes.process_name Processes.process Processes.parent_process_name
  Processes.dest Processes.user |`drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `change_to_safe_mode_with_network_config_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: unknown
references:
- https://news.sophos.com/en-us/2021/08/09/blackmatter-ransomware-emerges-from-the-shadow-of-darkside/
tags:
  analytic_story:
  - BlackMatter Ransomware
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: bcdedit process with commandline $process$ to force safemode boot the $dest$
  mitre_attack_id:
  - T1490
  observable:
  - name: user
    type: User
    role:
    - Victim
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.process_name
  - Processes.process
  - Processes.parent_process_name
  - Processes.parent_process
  - Processes.dest
  - Processes.user
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1552.002/autoadminlogon/windows-sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
