name: Disabling CMD Application
id: ff86077c-9212-11eb-a1e6-acde48001122
version: 6
date: '2024-05-16'
author: Steven Dick, Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic detects modifications to the registry that disable
  the CMD prompt application. It leverages data from the Endpoint.Registry data model,
  specifically looking for changes to the "DisableCMD" registry value. This activity
  is significant because disabling CMD can hinder an analyst's ability to investigate
  and remediate threats, a tactic often used by malware such as RATs, Trojans, or
  Worms. If confirmed malicious, this could prevent security teams from using CMD
  for directory and file traversal, complicating incident response and allowing the
  attacker to maintain persistence.
data_source:
- Sysmon EventID 12
- Sysmon EventID 13
search: '| tstats `security_content_summariesonly` count FROM datamodel=Endpoint.Registry
  WHERE (Registry.registry_path= "*\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DisableCMD"
  Registry.registry_value_data = "0x00000001") BY _time span=1h Registry.dest Registry.user
  Registry.registry_path Registry.registry_key_name Registry.registry_value_name Registry.registry_value_data
  Registry.process_guid | `drop_dm_object_name(Registry)` | where isnotnull(registry_value_data)
  | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)` | `disabling_cmd_application_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the registry value name, registry path, and registry value data from your
  endpoints. If you are using Sysmon, you must have at least version 2.0 of the offical
  Sysmon TA. https://splunkbase.splunk.com/app/5709
known_false_positives: admin may disable this application for non technical user.
references:
- https://any.run/report/ea4ea08407d4ee72e009103a3b77e5a09412b722fdef67315ea63f22011152af/a866d7b1-c236-4f26-a391-5ae32213dfc4#registry
tags:
  analytic_story:
  - Windows Defense Evasion Tactics
  - Windows Registry Abuse
  - NjRAT
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: The Windows command prompt was disabled on $dest$ by $user$.
  mitre_attack_id:
  - T1562.001
  - T1562
  - T1112
  observable:
  - name: user
    type: User
    role:
    - Victim
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Registry.dest
  - Registry.registry_value_name
  - Registry.registry_key_name
  - Registry.registry_path
  - Registry.registry_value_data
  - Registry.process_guid
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562.001/win_app_defender_disabling/windows-sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
