name: Linux Possible Append Command To Profile Config File
id: 9c94732a-61af-11ec-91e3-acde48001122
version: 2
date: '2024-05-30'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic detects suspicious command-lines that modify user
  profile files to automatically execute scripts or executables upon system reboot.
  It leverages data from Endpoint Detection and Response (EDR) agents, focusing on
  command-line executions involving profile files like ~/.bashrc and /etc/profile.
  This activity is significant as it indicates potential persistence mechanisms used
  by adversaries to maintain access to compromised hosts. If confirmed malicious,
  this could allow attackers to execute arbitrary code upon reboot, leading to persistent
  control over the system and potential further exploitation.
data_source:
- Sysmon for Linux EventID 1
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where Processes.process = "*echo*"
  AND Processes.process IN("*~/.bashrc", "*~/.bash_profile", "*/etc/profile", "~/.bash_login",
  "*~/.profile", "~/.bash_logout") by Processes.dest Processes.user Processes.parent_process_name
  Processes.process_name Processes.process Processes.process_id Processes.parent_process_id
  Processes.process_guid | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `linux_possible_append_command_to_profile_config_file_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: Administrator or network operator can use this commandline
  for automation purposes. Please update the filter macros to remove false positives.
references:
- https://unix.stackexchange.com/questions/129143/what-is-the-purpose-of-bashrc-and-how-does-it-work
- https://attack.mitre.org/techniques/T1546/004/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  asset_type: Endpoint
  confidence: 70
  impact: 70
  message: a commandline $process$ that may modify profile files in $dest$
  mitre_attack_id:
  - T1546.004
  - T1546
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.dest
  - Processes.user
  - Processes.parent_process_name
  - Processes.process_name
  - Processes.process
  - Processes.process_id
  - Processes.parent_process_id
  risk_score: 49
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1546.004/linux_init_profile/sysmon_linux.log
    source: Syslog:Linux-Sysmon/Operational
    sourcetype: sysmon:linux
