name: Linux Possible Access Or Modification Of sshd Config File
id: 7a85eb24-72da-11ec-ac76-acde48001122
version: 1
date: '2022-01-11'
author: Teoderick Contreras, Splunk
type: Anomaly
datamodel:
- Endpoint
description: This analytic is to look for suspicious process command-line that might
  be accessing or modifying sshd_config. This file is the ssh configuration file that
  might be modify by threat actors or adversaries to redirect port connection, allow
  user using authorized key generated during attack. This anomaly detection might
  catch noise from administrator auditing or modifying ssh configuration file. In
  this scenario filter is needed
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where Processes.process_name IN("cat",
  "nano*","vim*", "vi*")  AND Processes.process IN("*/etc/ssh/sshd_config") by Processes.dest
  Processes.user Processes.parent_process_name Processes.process_name Processes.process
  Processes.process_id Processes.parent_process_id | `drop_dm_object_name(Processes)`
  | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)` | `linux_possible_access_or_modification_of_sshd_config_file_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you can use the Add-on for Linux Sysmon from
  Splunkbase.
known_false_positives: Administrator or network operator can use this commandline
  for automation purposes. Please update the filter macros to remove false positives.
references:
- https://www.hackingarticles.in/ssh-penetration-testing-port-22/
- https://attack.mitre.org/techniques/T1098/004/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  automated_detection_testing: passed
  cis20:
  - CIS 3
  - CIS 5
  - CIS 16
  confidence: 50
  context:
  - Source:Endpoint
  - Stage:Privilege Escalation
  - Stage:Persistence
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1098.004/ssh_authorized_keys/sysmon_linux.log
  impact: 50
  kill_chain_phases:
  - Exploitation
  message: a commandline $process$ executed on $dest$
  mitre_attack_id:
  - T1098.004
  - T1098
  nist:
  - DE.CM
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.dest
  - Processes.user
  - Processes.parent_process_name
  - Processes.process_name
  - Processes.process
  - Processes.process_id
  - Processes.parent_process_id
  risk_score: 25
  security_domain: endpoint
  asset_type: Endpoint
