name: Linux Auditd System Network Configuration Discovery
id: 5db16825-81bd-4923-a8d6-d6a13a59832a
version: 1
date: '2024-09-04'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic detects suspicious system network configuration
  discovery activities, which may indicate an adversary's attempt to gather information
  about the network environment. Such actions typically involve commands or tools
  used to identify network interfaces, routing tables, and active connections. Detecting
  these activities is crucial, as they often precede more targeted attacks like lateral
  movement or data exfiltration. By identifying unusual or unauthorized network discovery
  efforts, this analytic helps security teams to swiftly detect and respond to potential
  reconnaissance operations, mitigating the risk of further compromise.
data_source:
- Linux Auditd Syscall
search: '`linux_auditd` type=SYSCALL comm IN ("arp", "ifconfig", "ip", "netstat",
  "firewall-cmd", "ufw", "iptables", "ss", "route") | bucket _time span=15m | rename
  host as dest | stats dc(comm) as unique_commands, values(comm) as comm, values(exe)
  as exe, values(SYSCALL) as SYSCALL, values(UID) as UID, values(ppid) as ppid, values(pid)
  as pid, count, min(_time) as firstTime, max(_time) as lastTime by success dest |
  where unique_commands >= 4 | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | `linux_auditd_system_network_configuration_discovery_filter`'
how_to_implement: To implement this detection, the process begins by ingesting auditd
  data, that consist SYSCALL, TYPE, EXECVE and PROCTITLE events, which captures command-line
  executions and process details on Unix/Linux systems. These logs should be ingested
  and processed using Splunk Add-on for Unix and Linux (https://splunkbase.splunk.com/app/833),
  which is essential for correctly parsing and categorizing the data. The next step
  involves normalizing the field names  to match the field names set by the Splunk
  Common Information Model (CIM) to ensure consistency across different data sources
  and enhance the efficiency of data modeling. This approach enables effective monitoring
  and detection of linux endpoints where auditd is deployed
known_false_positives: Administrator or network operator can use this application
  for automation purposes. Please update the filter macros to remove false positives.
references:
- https://www.splunk.com/en_us/blog/security/deep-dive-on-persistence-privilege-escalation-technique-and-detection-in-linux-platform.html
tags:
  analytic_story:
  - Linux Living Off The Land
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  - Compromised Linux Host
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: A SYSCALL - [$comm$] event was executed on host - [$dest$] to discover system network configuration.
  mitre_attack_id:
  - T1016
  observable:
  - name: dest
    type: Endpoint
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - comm
  - exe
  - SYSCALL
  - UID
  - ppid
  - pid
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1016/linux_auditd_net_tool/linux_auditd_net_tool.log
    source: /var/log/audit/audit.log
    sourcetype: linux:audit
