name: Linux Possible Append Command To At Allow Config File
id: 7bc20606-5f40-11ec-a586-acde48001122
version: 1
date: '2021-12-17'
author: Teoderick Contreras, Splunk
type: Anomaly
datamodel:
- Endpoint
description: This analytic looks for suspicious commandline that may use to append user entry to /etc/at.allow or /etc/at.deny.
  These 2 files are commonly abused by malware, adversaries or red teamers to persist on the targeted or compromised host. 
  These config file can restrict user that can only execute at application (another schedule task application in linux). attacker can 
  create a user or add the compromised username to that config file to execute at to schedule it malicious code. This anomaly detection 
  can be a good indicator to investigate further the entry in created config file and who created it to verify if it is a false positive.   
search: '| tstats `security_content_summariesonly` count from datamodel=Endpoint.Processes 
  where Processes.process = "*echo*" AND Processes.process IN("*/etc/at.allow", "*/etc/at.deny")
  by Processes.dest Processes.user Processes.parent_process_name Processes.process_name Processes.process Processes.process_id Processes.parent_process_id Processes.process_guid
  | `drop_dm_object_name(Processes)` 
  | `security_content_ctime(firstTime)` 
  | `security_content_ctime(lastTime)` 
  | `linux_possible_append_command_to_at_allow_config_file_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA. 
known_false_positives: Administrator or network operator can use this commandline for automation purposes. filter is needed 
references:
-  https://linuxize.com/post/at-command-in-linux/
- https://attack.mitre.org/techniques/T1053/001/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1053.001/sysmon_linux.log
  kill_chain_phases:
  - Privilege Escalation
  mitre_attack_id:
  - T1053.001
  - T1053
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.dest 
  - Processes.user 
  - Processes.parent_process_name 
  - Processes.process_name 
  - Processes.process 
  - Processes.process_id 
  - Processes.parent_process_id
  security_domain: endpoint
  impact: 30
  confidence: 30 
  # (impact * confidence)/100
  risk_score: 9
  context:
  - source:endpoint
  - stage:Privilege Escalation Persistence
  message: a commandline $process$ that may modify at allow config file in $dest$
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  nist:
  - DE.CM
  cis20:
  - CIS 3
  - CIS 5
  - CIS 16
