name: Linux Account Manipulation Of SSH Config and Keys
id: 73a56508-1cf5-4df7-b8d9-5737fbdc27d2
version: 3
date: '2024-05-23'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic detects the deletion of SSH keys on a Linux machine.
  It leverages filesystem event logs to identify when files within "/etc/ssh/*" or
  "~/.ssh/*" are deleted. This activity is significant because attackers may delete
  or modify SSH keys to evade security measures or as part of a destructive payload,
  similar to the AcidRain malware. If confirmed malicious, this behavior could lead
  to impaired security features, hindered forensic investigations, or further unauthorized
  access, necessitating immediate investigation to identify the responsible process
  and user.
data_source:
- Sysmon for Linux EventID 11
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime FROM datamodel=Endpoint.Filesystem where Filesystem.action=deleted AND
  Filesystem.file_path IN ("/etc/ssh/*", "~/.ssh/*") by _time span=1h Filesystem.file_name
  Filesystem.file_path Filesystem.dest Filesystem.process_guid Filesystem.action |
  `drop_dm_object_name(Filesystem)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`|
  `linux_account_manipulation_of_ssh_config_and_keys_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you can use the Add-on for Linux Sysmon from
  Splunkbase.
known_false_positives: Administrator or network operator can execute this command.
  Please update the filter macros to remove false positives.
references:
- https://www.sentinelone.com/labs/acidrain-a-modem-wiper-rains-down-on-europe/
tags:
  analytic_story:
  - AcidRain
  asset_type: Endpoint
  confidence: 70
  impact: 70
  message: SSH Config and keys are deleted on $dest$ by Process GUID - $process_guid$
  mitre_attack_id:
  - T1485
  - T1070.004
  - T1070
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Filesystem.dest
  - Filesystem.file_create_time
  - Filesystem.file_name
  - Filesystem.process_guid
  - Filesystem.file_path
  - Filesystem.action
  risk_score: 49
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/acidrain/sysmon_linux.log
    source: Syslog:Linux-Sysmon/Operational
    sourcetype: sysmon:linux
