name: MacOS - Re-opened Applications
id: 40bb64f9-f619-4e3d-8732-328d40377c4b
version: 2
date: '2024-05-14'
author: Jamie Windley, Splunk
status: experimental
type: TTP
description: The following analytic identifies processes referencing plist files that
  determine which applications are re-opened when a user reboots their MacOS machine.
  It leverages data from Endpoint Detection and Response (EDR) agents, focusing on
  process names and parent processes related to "com.apple.loginwindow." This activity
  is significant because it can indicate attempts to persist across reboots, a common
  tactic used by attackers to maintain access. If confirmed malicious, this could
  allow an attacker to execute code or maintain persistence on the affected system,
  potentially leading to further compromise.
data_source:
- Sysmon EventID 1
search: '| tstats `security_content_summariesonly` count values(Processes.process)
  as process values(Processes.parent_process) as parent_process min(_time) as firstTime
  max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process="*com.apple.loginwindow*"
  by Processes.user Processes.process_name Processes.parent_process_name Processes.dest
  | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | `macos___re_opened_applications_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: At this stage, there are no known false positives. During testing,
  no process events refering the com.apple.loginwindow.plist files were observed during
  normal operation of re-opening applications on reboot. Therefore, it can be asumed
  that any occurences of this in the process events would be worth investigating.
  In the event that the legitimate modification by the system of these files is in
  fact logged to the process log, then the process_name of that process can be added
  to an allow list.
references: []
tags:
  analytic_story:
  - ColdRoot MacOS RAT
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: tbd
  observable:
  - name: user
    type: User
    role:
    - Victim
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.process
  - Processes.parent_process
  - Processes.user
  - Processes.process_name
  - Processes.parent_process_name
  - Processes.dest
  risk_score: 25
  security_domain: threat
