name: Office Application Spawn Regsvr32 process
id: 2d9fc90c-f11f-11eb-9300-acde48001122
version: 1
date: '2021-07-30'
author: Teoderick Contreras, Splunk
type: batch
datamodel:
- Endpoint
description: this detection was designed to identifies suspicious spawned process
  of known MS office application due to macro or malicious code. this technique can
  be seen in so many malware like Icedid that used MS office as its weapon or attack
  vector to initially infect the machines.
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where (Processes.parent_process_name
  = "winword.exe" OR Processes.parent_process_name = "excel.exe" OR Processes.parent_process_name
  = "powerpnt.exe" OR Processes.parent_process_name = "outlook.exe") Processes.process_name=regsvr32.exe
  by Processes.parent_process_name Processes.parent_process Processes.process_name
  Processes.process Processes.process_id Processes.process_guid Processes.user Processes.dest
  | `drop_dm_object_name("Processes")` | `security_content_ctime(firstTime)` |`security_content_ctime(lastTime)`
  | `office_application_spawn_regsvr32_process_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA.
known_false_positives: unknown
references:
- https://www.joesandbox.com/analysis/380662/0/html
tags:
  analytic_story:
  - Icedid
  automated_detection_testing: passed
  confidence: 90
  context:
  - Source:Endpoint
  - Stage:Execution
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/icedid/phish_icedid/windows-sysmon.log
  impact: 70
  kill_chain_phases:
  - Exploitation
  message: Office application spawning regsvr32.exe on $dest$
  mitre_attack_id:
  - T1566.001
  observable:
  - name: dest
    type: Endpoint
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.parent_process_name
  - Processes.parent_process
  - Processes.process_name
  - Processes.process
  - Processes.process_id
  - Processes.process_guid
  - Processes.user
  - Processes.dest
  risk_score: 63
  security_domain: endpoint
