name: Office Application Spawn rundll32 process
id: 958751e4-9c5f-11eb-b103-acde48001122
version: 5
date: '2024-05-25'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic identifies instances where an Office application
  spawns a rundll32 process, which is often indicative of macro execution or malicious
  code. This detection leverages data from Endpoint Detection and Response (EDR) agents,
  focusing on process creation events where the parent process is a known Office application.
  This activity is significant because it is a common technique used by malware, such
  as Trickbot, to initiate infections. If confirmed malicious, this behavior could
  lead to code execution, further system compromise, and potential data exfiltration.
data_source:
- Sysmon EventID 1
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where (Processes.parent_process_name
  = "winword.exe" OR Processes.parent_process_name = "excel.exe" OR Processes.parent_process_name
  = "powerpnt.exe" OR Processes.parent_process_name= "onenote.exe" OR Processes.parent_process_name
  = "onenotem.exe" OR Processes.parent_process_name = "onenoteviewer.exe" OR Processes.parent_process_name
  = "onenoteim.exe" OR Processes.parent_process_name = "msaccess.exe") AND `process_rundll32`
  by Processes.parent_process Processes.process_name Processes.process_id Processes.process_guid
  Processes.process Processes.user Processes.dest | `drop_dm_object_name("Processes")`
  | `security_content_ctime(firstTime)` |`security_content_ctime(lastTime)` | `office_application_spawn_rundll32_process_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: unknown
references:
- https://any.run/malware-trends/trickbot
- https://any.run/report/47561b4e949041eff0a0f4693c59c81726591779fe21183ae9185b5eb6a69847/aba3722a-b373-4dae-8273-8730fb40cdbe
- https://www.joesandbox.com/analysis/702680/0/html
- https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/trojanized-onenote-document-leads-to-formbook-malware/
tags:
  analytic_story:
  - Spearphishing Attachments
  - Trickbot
  - IcedID
  - AgentTesla
  - NjRAT
  asset_type: Endpoint
  confidence: 90
  impact: 70
  message: Office application spawning rundll32.exe on $dest$
  mitre_attack_id:
  - T1566
  - T1566.001
  observable:
  - name: dest
    type: Endpoint
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - Processes.dest
  - Processes.user
  - Processes.parent_process_name
  - Processes.parent_process
  - Processes.original_file_name
  - Processes.process_name
  - Processes.process
  - Processes.process_id
  - Processes.parent_process_path
  - Processes.process_path
  - Processes.parent_process_id
  risk_score: 63
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1566.001/datasets/windows-sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
