name: Sdelete Application Execution
id: 31702fc0-2682-11ec-85c3-acde48001122
version: 2
date: '2024-05-23'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic detects the execution of the sdelete.exe application,
  a Sysinternals tool often used by adversaries to securely delete files and remove
  forensic evidence from a targeted host. This detection leverages data from Endpoint
  Detection and Response (EDR) agents, focusing on process execution logs. Monitoring
  this activity is crucial as sdelete.exe is not commonly used in regular operations
  and its presence may indicate an attempt to cover malicious activities. If confirmed
  malicious, this could lead to the loss of critical forensic data, hindering incident
  response and investigation efforts.
data_source:
- Sysmon EventID 1
search: '| tstats `security_content_summariesonly` values(Processes.process) as process
  values(Processes.parent_process) as parent_process values(Processes.process_id)
  as process_id count min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes
  where `process_sdelete` by  Processes.process_name Processes.original_file_name
  Processes.dest Processes.user Processes.parent_process_name Processes.parent_process
  | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | `sdelete_application_execution_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: user may execute and use this application
references:
- https://app.any.run/tasks/956f50be-2c13-465a-ac00-6224c14c5f89/
tags:
  analytic_story:
  - Masquerading - Rename System Utilities
  asset_type: Endpoint
  confidence: 70
  impact: 70
  message: sdelete process $process_name$ executed in $dest$
  mitre_attack_id:
  - T1485
  - T1070.004
  - T1070
  observable:
  - name: dest
    type: Endpoint
    role:
    - Victim
  - name: user
    type: User
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.dest
  - Processes.user
  - Processes.parent_process_name
  - Processes.parent_process
  - Processes.original_file_name
  - Processes.process_name
  - Processes.process
  - Processes.process_id
  - Processes.parent_process_path
  - Processes.process_path
  - Processes.parent_process_id
  risk_score: 49
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1485/sdelete/sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
