name: Windows Modify Registry Disabling WER Settings
id: 21cbcaf1-b51f-496d-a0c1-858ff3070452
version: 2
date: '2024-05-12'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic detects modifications in the Windows registry
  to disable Windows Error Reporting (WER) settings. It leverages data from the Endpoint.Registry
  datamodel, specifically monitoring changes to registry paths related to WER with
  a value set to "0x00000001". This activity is significant as adversaries may disable
  WER to suppress error notifications, hiding the presence of malicious activities.
  If confirmed malicious, this could allow attackers to operate undetected, potentially
  leading to prolonged persistence and further exploitation within the environment.
data_source:
- Sysmon EventID 12
- Sysmon EventID 13
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime FROM datamodel=Endpoint.Registry where Registry.registry_path= "*\\SOFTWARE\\Microsoft\\Windows\\Windows
  Error Reporting\\disable*" Registry.registry_value_data="0x00000001" by Registry.registry_key_name
  Registry.user Registry.registry_path Registry.registry_value_data Registry.action
  Registry.dest | `drop_dm_object_name(Registry)` | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `windows_modify_registry_disabling_wer_settings_filter`'
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints into the `Endpoint` datamodel in the `Registry` node. Also make sure
  that this registry was included in your config files ex. sysmon config to be monitored.
known_false_positives: Administrators may enable or disable this feature that may
  cause some false positive, however is not common. Filter as needed.
references:
- https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-remoteassistance-exe-fallowtogethelp
- https://app.any.run/tasks/a6f2ffe2-e6e2-4396-ae2e-04ea0143f2d8/
tags:
  analytic_story:
  - Azorult
  - CISA AA23-347A
  asset_type: Endpoint
  confidence: 70
  impact: 70
  message: the registry for WER settings was modified to be disabled on $dest$.
  mitre_attack_id:
  - T1112
  observable:
  - name: dest
    type: Endpoint
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Registry.registry_key_name
  - Registry.registry_path
  - Registry.user
  - Registry.dest
  - Registry.registry_value_name
  - Registry.action
  risk_score: 49
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/azorult/sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
    update_timestamp: true
