name: Windows Application Layer Protocol RMS Radmin Tool Namedpipe
id: b62a6040-49f4-47c8-b3f6-fc1adb952a33
version: 2
date: '2024-05-18'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: The following analytic detects the use of default or publicly known named
  pipes associated with the RMX remote admin tool. It leverages Sysmon EventCodes
  17 and 18 to identify named pipe creation and connection events. This activity is
  significant as the RMX tool has been abused by adversaries and malware like Azorult
  to collect data from targeted hosts. If confirmed malicious, this could indicate
  unauthorized remote administration capabilities, leading to data exfiltration or
  further compromise of the affected system. Immediate investigation is required to
  determine the legitimacy of this tool's presence.
data_source:
- Sysmon EventID 17
- Sysmon EventID 18
search: '`sysmon` EventCode IN (17, 18) EventType IN ( "CreatePipe", "ConnectPipe")
  PipeName IN ("\\RManFUSServerNotify32", "\\RManFUSCallbackNotify32", "\\RMSPrint*")
  | stats  min(_time) as firstTime max(_time) as lastTime count by Image EventType
  ProcessId PipeName dest UserID | rename UserID as user | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `windows_application_layer_protocol_rms_radmin_tool_namedpipe_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA.
known_false_positives: False positives may be present. Filter based on pipe name or
  process.
references:
- https://app.any.run/tasks/a6f2ffe2-e6e2-4396-ae2e-04ea0143f2d8/
- https://attack.mitre.org/techniques/T1071/
tags:
  analytic_story:
  - Azorult
  asset_type: Endpoint
  confidence: 90
  impact: 90
  message: possible RMS admin tool named pipe was created in endpoint $dest$
  mitre_attack_id:
  - T1071
  observable:
  - name: dest
    type: Endpoint
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Image
  - EventType
  - ProcessId
  - PipeName
  - dest
  - UserID
  risk_score: 81
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: 
      https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/azorult/sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
    update_timestamp: true
